### ISSUE TITLE
New fix

### ISSUE THREAD

**Issue by LoranKloeze** [LoranKloeze/WhatsAllApp#104]
It's a while ago but i have picked up the development of this tool again 😊
Right now I have most of the functionality working and i am testing the online presence check.
Let's see where this goes.

If you want to support me, please think about sponsoring me. I have just set up my [sponsor profile](https://github.com/sponsors/LoranKloeze)

**Comment by ohari5336** [comment]
I am happy for you to start again maintain this :)

**Comment by ginevra2013** [comment]
Big Loran, welcome back, we need you. I downloaded the file, but it doesn't work.

**Comment by LoranKloeze** [comment]
> Big Loran, welcome back, we need you. I downloaded the file, but it doesn't work.

Can you please create a separate issue with the error messages you see in the console? Thx!

**Comment by ginevra2013** [comment]
The top bar does not appear. I send you the screenshots. Where should I look for the error message? I'm sorry
[Whatsapp.docx](https://github.com/LoranKloeze/WhatsAllApp/files/6154628/Whatsapp.docx)

**Comment by LoranKloeze** [comment]
@ginevra2013, I have deleted your comment:

- Create a separate issue
- Ctrl-c/v the console error (check Google https://developers.google.com/web/tools/chrome-devtools/open)
- Don't use docx files, it is too often used by cyber criminals, just past the screenshots in the issue

Don't take this the wrong way but if you don't know what the Chrome console is you better might look for a more production ready tool.
