### ISSUE TITLE
Error -  the bar does not open

### ISSUE THREAD

**Issue by ginevra2013** [LoranKloeze/WhatsAllApp#106]
Loran Thanks for the info. Do you attach a scrennshot of the console? did I get it right?

**Comment by LoranKloeze** [comment]
I did not attach anything?

Please read this: https://wiredcraft.com/blog/how-we-write-our-github-issues/

**Comment by ginevra2013** [comment]
I have not attached because I did not know what kind of file, so as not to be mistaken. I'm sorry. I am attaching the screenshot then. Thank you
![screen 3](https://user-images.githubusercontent.com/43003469/111450722-f84db200-8710-11eb-8520-1aa0e431020f.jpg)
![Screen 2](https://user-images.githubusercontent.com/43003469/111450736-fbe13900-8710-11eb-8c31-a4fb63f41363.jpg)
![Screen 1](https://user-images.githubusercontent.com/43003469/111450747-ff74c000-8710-11eb-876e-2bb8931fbd3c.jpg)
![screen 4](https://user-images.githubusercontent.com/43003469/111450762-03a0dd80-8711-11eb-9948-08813c7a1d14.jpg)

**Comment by LoranKloeze** [comment]
Can you filter the Chrome console to only show errors?

**Comment by ginevra2013** [comment]
scheduler.development.js:298 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
eval @ scheduler.development.js:298
react-dom.development.js:26239 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
​ Wapp DOM is not ready in time, exiting WhatsAllApp...
eval @ webpack://whats_all_…/./src/index.js?:37
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/styled-components/dist/styled-components.browser.esm.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/popper.js/dist/esm/popper.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/parsePhoneNumber.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/parsePhoneNumber_.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/parse_.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/constants.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/ParseError.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/metadata.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/tools/semver-compare.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/helpers/isViablePhoneNumber.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/helpers/extension/createExtensionPattern.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/helpers/extension/extractExtension.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/parseIncompletePhoneNumber.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/helpers/parseDigits.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/isPossibleNumber_.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/helpers/checkNumberLength.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/helpers/mergeArrays.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/helpers/RFC3966.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/PhoneNumber.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/validate_.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/helpers/matchesEntirely.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/helpers/getNumberType.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/format_.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/helpers/formatNationalNumberUsingFormat.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/helpers/applyInternationalSeparatorStyle.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/helpers/getIddPrefix.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/helpers/extractCountryCallingCode.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/helpers/stripIddPrefix.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/helpers/extractCountryCallingCodeFromInternationalNumberWithoutPlusSign.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/helpers/extractNationalNumber.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/helpers/extractNationalNumberFromPossiblyIncompleteNumber.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/helpers/getCountryByCallingCode.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/parsePhoneNumberFromString.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/parsePhoneNumberFromString_.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/isValidPhoneNumber.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/isPossiblePhoneNumber.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/findNumbers.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/findNumbers_.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/PhoneNumberMatcher.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/findNumbers/RegExpCache.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/findNumbers/LRUCache.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/findNumbers/util.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/findNumbers/utf-8.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/findNumbers/Leniency.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/findNumbers/parsePreCandidate.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/findNumbers/isValidPreCandidate.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/findNumbers/isValidCandidate.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/searchNumbers.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/findPhoneNumbersInText.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/searchPhoneNumbersInText.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/AsYouType.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/AsYouTypeState.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/AsYouTypeFormatter.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/AsYouTypeFormatter.util.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/AsYouTypeFormatter.complete.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/AsYouTypeParser.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/getCountries.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/getExampleNumber.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/formatIncompletePhoneNumber.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/parse.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/format.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/getNumberType.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/isPossibleNumber.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/validate.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/isValidNumberForRegion.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/isValidNumberForRegion_.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/findPhoneNumbers.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/findPhoneNumbers_.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by ginevra2013** [comment]
I hope you asked me this, sorry if I was wrong

**Comment by LoranKloeze** [comment]
I asked you to filter the console output so that only errors show up but you paste the console output full of warnings...

I am really sorry but your knowledge of Chrome, its development tools and Javascript is not at a level that I can help you. 
Try to learn something about the topics I mentioned. Then try it again. :)
