### ISSUE TITLE
console doesn't appear

### ISSUE THREAD

**Issue by CoraatB3ware** [LoranKloeze/WhatsAllApp#107]
First of all, thank you Loran for continuing to work on the tool. I really appreciate it very much. 

Unfortunately it doesn´t work for me ... Please find the errorlog attached... Do you have any ideas?
[whatsallapp.txt.txt](https://github.com/LoranKloeze/WhatsAllApp/files/6177761/whatsallapp.txt.txt)

**Comment by LoranKloeze** [comment]
Waiting for other people to confirm.

**Comment by LoranKloeze** [comment]
Please try it again using master branch
