### ISSUE TITLE
Can not see the orange page

### ISSUE THREAD

**Issue by letty23** [LoranKloeze/WhatsAllApp#108]
Only the original WhatsApp Webb appears. You need a older chrome version?

**Comment by LoranKloeze** [comment]
Did you follow these steps?

1. Click 'clone or download' and choose to download the ZIP file
2. Extract the folder from the ZIP file
3. Open up chrome://extensions/
4. Enable developer mode at the top of the screen by clicking the slider
5. Click 'load unpacked extension'
6. **Select the dist/ folder from step 2**
7. The extension should appear at the top of the list
8. Refresh your WhatsApp web
9. An orange slider should appear at the top of the screen

**Comment by letty23** [comment]
Yes i follow these steps. The extensions apperar in the selection, but when i refresh the Whatsapp Web nothing changes.

**Comment by LoranKloeze** [comment]
Please post the console output of the developer tools

**Comment by letty23** [comment]
Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
eval @ scheduler.development.js:298
eval @ scheduler.development.js:843
./node_modules/scheduler/cjs/scheduler.development.js @ bundle.js:4551
__webpack_require__ @ bundle.js:4661
eval @ index.js:4
./node_modules/scheduler/index.js @ bundle.js:4562
__webpack_require__ @ bundle.js:4661
eval @ react-dom.development.js:18
eval @ react-dom.development.js:26256
./node_modules/react-dom/cjs/react-dom.development.js @ bundle.js:3221
__webpack_require__ @ bundle.js:4661
eval @ index.js:32
./node_modules/react-dom/index.js @ bundle.js:3232
__webpack_require__ @ bundle.js:4661
eval @ index.js:7
./src/index.js @ bundle.js:238
__webpack_require__ @ bundle.js:4661
(anonymous) @ bundle.js:4742
(anonymous) @ bundle.js:4744
react-dom.development.js:26239 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
Log.js:9 Starting WhatsAllApp
Log.js:9 Polling Wapp DOM
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/styled-components/dist/styled-components.browser.esm.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/popper.js/dist/esm/popper.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/parsePhoneNumber.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/parsePhoneNumber_.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://whats_all_app_community_edition/node_modules/libphonenumber-js/es6/parse_.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME


this is always repeated

**Comment by LoranKloeze** [comment]
It never says 'Waiting for Wapp DOM...'?

**Comment by letty23** [comment]
Oh sure sorry, thats the last line. I forgot this. 
There is Waiting for Wapp DOM... and the counter keeps counting up to 218 and then it appears: 

index.js:37 Wapp DOM is not ready in time, exiting WhatsAllApp...
eval @ index.js:37

**Comment by LoranKloeze** [comment]
Can you paste this in the console and tell me what the return value is:

```document.querySelector('[aria-label="Chat list. Press right arrow key on a chat to open chat context menu."]')```

**Comment by letty23** [comment]
The console outputs: null

**Comment by LoranKloeze** [comment]
There's the problem. 😊
I'm working on it.

**Comment by LoranKloeze** [comment]
Please try it again using master branch

**Comment by letty23** [comment]
Thanks a lot bro, now it works.
