### ISSUE TITLE
Whatsapp Profile Image Download

### ISSUE THREAD

**Issue by whatsappapi** [LoranKloeze/WhatsAllApp#11]
I want to download profile images after click start indexer. 

 imgTag.src = d.img;
 var image = d.img;
chrome.downloads.download({
url: image, filename: "image.jpg" // Optional
});

I tried like this but not working. Repo owner blocked me on twitter. I only say "Hi Sir". 

Can someone help please?

**Comment by LoranKloeze** [comment]
I'm sorry, it's because of a block script that checks nr of tweets and follower account.
I hope someone can help you out here.

**Comment by whatsappapi** [comment]
@gr4ssi can you help please?

**Comment by yotam180** [comment]
I believe your issue is not really with interfacing to WhatsApp, but rather downloading the images.
[This](https://stackoverflow.com/questions/3644938/initiating-a-download-with-javascript) might be helpful (?)

**Comment by whatsappapi** [comment]
@yotam180 i want a loop for downloading whatsapp profile images with whatsapp web.

**Comment by gr4ssi** [comment]
Sorry, I don't know JavaScript, I'd rather write the links to the images into a textfile and then use wget, but that is just me.  ;-)

**Comment by gr4ssi** [comment]
The loop is here somewhere:
For number in numbers do something:
https://gist.github.com/gr4ssi/e6f4288f5eff2154f7a54e16958e9dc9

**Comment by yotam180** [comment]
@gr4ssi Writing to a text file via Javascript (or via web entirely) will be problematic... 😕

**Comment by gr4ssi** [comment]
What, yeah sure. That's why I gotta pass on this honorable task ;-)

**Comment by LoranKloeze** [comment]
I've created a button so you can download numbers + pictures via a zip file. Give it a try :)

**Comment by LoranKloeze** [comment]
If there are any bugs, please open a new issue :)
