### ISSUE TITLE
orangefarbener Schieberegler nicht da

### ISSUE THREAD

**Issue by michaelb1665** [LoranKloeze/WhatsAllApp#114]
orangefarbener Schieberegler nicht da. Hilfe!!!!!

**Comment by LoranKloeze** [comment]
Tell me what you've tried so far.

**Comment by michaelb1665** [comment]
Habe alles wie beschrieben gemacht.
Klicken Sie auf "Klonen oder Herunterladen" und laden Sie die ZIP-Datei herunter
Extrahieren Sie den Ordner aus der ZIP-Datei
Öffnen Sie chrome: // extensions /
Aktivieren Sie den Entwicklermodus oben auf dem Bildschirm, indem Sie auf den Schieberegler klicken
Klicken Sie auf "Entpackte Erweiterung laden".
Wählen Sie den dist / Ordner aus Schritt 2 aus
Die Erweiterung sollte oben in der Liste angezeigt werden
Aktualisieren Sie Ihr WhatsApp-Web
Oben auf dem Bildschirm sollte ein orangefarbener Schieberegler angezeigt werden

**Comment by michaelb1665** [comment]
Klicken Sie auf "Klonen oder Herunterladen" und laden Sie die ZIP-Datei herunter
Extrahieren Sie den Ordner aus der ZIP-Datei
Öffnen Sie chrome: // extensions /
Aktivieren Sie den Entwicklermodus oben auf dem Bildschirm, indem Sie auf den Schieberegler klicken
Klicken Sie auf "Entpackte Erweiterung laden".
Wählen Sie den dist / Ordner aus Schritt 2 aus
Die Erweiterung sollte oben in der Liste angezeigt werden
Aktualisieren Sie Ihr WhatsApp-Web
Oben auf dem Bildschirm sollte ein orangefarbener Schieberegler angezeigt werden

orangener Schiebregler nicht da!

**Comment by LoranKloeze** [comment]
Click 'clone or download' and choose to download the ZIP file
Extract the folder from the ZIP file
Open up chrome://extensions/
Enable developer mode at the top of the screen by clicking the slider
Click 'load unpacked extension'
------> **Select the dist/ folder from step 2** <------ 
The extension should appear at the top of the list
Refresh your WhatsApp web
An orange slider should appear at the top of the screen

A lot of times people forget ^^^ that step

**Comment by michaelb1665** [comment]
alles so gemacht. In der Erweiterung auch zu sehen, aber wo ist der orangene Regler?

**Comment by michaelb1665** [comment]
WhatsAllApp Community Edition
0.0.1
UI overlay for WhatsApp Web to enumerate phone numbers, profile pics, online statuses and status texts.
ID: edglfeclpkfnldnihjcebbhcfihobboa
Ansichten prüfen
Hintergrundseite
