### ISSUE TITLE
Slider not showing

### ISSUE THREAD

**Issue by pcintra11** [LoranKloeze/WhatsAllApp#116]
I've installed the extension and reload the page. The icon is orange and it seems to be ok, but the slider is not showing.  Why? 
I even can enable and disable by the extension icon.

**Comment by pcintra11** [comment]
![image](https://user-images.githubusercontent.com/57155941/125066844-d8f4df00-e089-11eb-94af-3a8ca5d04d36.png)

**Comment by libiaoqiao** [comment]
Why can't I contact this author? I think he is an excellent IT worker.

**Comment by LoranKloeze** [comment]
Anyone else having this problem?

**Comment by ginevra2013** [comment]
Hi LoranKloeze, Same problem, for several days, the extension is not working.
Looking forward to your new intervention.
Thanksssssssssss

**Comment by LoranKloeze** [comment]
Please post the contents of the Chrome console, it probably contains errors

**Comment by Henk-007** [comment]
Hi LoranKloeze, same problem here. Here is the contents of the console log:

[web.whatsapp.com-1627387289476.log](https://github.com/LoranKloeze/WhatsAllApp/files/6885181/web.whatsapp.com-1627387289476.log)

**Comment by LoranKloeze** [comment]
I've updated the manifest and fixed a bug caused by an update from WhatsApp causing webpack chunks missing.
Please try it again.

**Comment by ginevra2013** [comment]
Thanks

Il mer 28 lug 2021, 14:50 Loran Kloeze ***@***.***> ha
scritto:

**Comment by Henk-007** [comment]
Thanks Loran.

**Comment by pcintra11** [comment]
Tks Loran !

**Comment by LoranKloeze** [comment]
Closing this, it's solved
