### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ginevra2013** [LoranKloeze/WhatsAllApp#125]
The orange bar is visible, but disappears when you search. Not working

**Comment by ginevra2013** [comment]
Loran, 
an update when will you do it? we also donated or am I wrong? thank you

**Comment by LoranKloeze** [comment]
Please provide some more info. What errors do you get?

**Comment by ginevra2013** [comment]
I ATTACH THE FILE, I HOPE THIS IS THE INFORMATION YOU NEED. OTHERWISE TELL ME WHAT
[web.whatsapp.com-1639413416384.log](https://github.com/LoranKloeze/WhatsAllApp/files/7705446/web.whatsapp.com-1639413416384.log)

**Comment by LoranKloeze** [comment]
https://github.com/LoranKloeze/WhatsAllApp/issues/124
