### ISSUE TITLE
Online/offline statuses not showing

### ISSUE THREAD

**Issue by karopass** [LoranKloeze/WhatsAllApp#13]
Hi!
Its working like charm till now. At this time its stopped working and not providing presence of numbers. Let me know if there any update regarding it.
Thanks

**Comment by LoranKloeze** [comment]
I tried it like 5 minutes ago and everything seems fine. I've use a freshly opened Web Whatsapp and ctrl-c/v'ed the script from 'ui.js' and pasted it to the console.

If it doesn't work anymore then the extension bugged out. I'd like to hear from other people who experience the same problem.

**Comment by karopass** [comment]
Hi @LoranKloeze !
Thanks for quick response. I have checked with different conditions and found that its work only for number which we have in our contact as well our number must saved in that numbers contact list. Can You please confirm its right or not? I have tried many time and found this.
Thanks

**Comment by mertxkaan** [comment]
Yes, I see that just in whatsappweb, Store object doesn't update "isOnline" status, if that number doesn't have our number in their contact list. If they have, everything is working. I think they made a security update a couple days ago.

**Comment by LoranKloeze** [comment]
You are correct. But the information about the online status still flows into Web WhatsApp, I can see it coming in through the websocket. I guess WA has changed something about the API. When I have the time, I'll look into it.

**Comment by eandreini** [comment]
It seems that online element is now named "__x_isOnline" instead that "isOnline". I changed it and it seems to work now

**Comment by eandreini** [comment]
I changed line 249 of ui.js with:
     if (m.__x_isOnline) {

**Comment by karopass** [comment]
Hi! @mertxkaan @LoranKloeze I have marked that if we send message to that number, its working. Let me know if anyone can find solution for it.
Thanks

**Comment by karopass** [comment]
@LoranKloeze Any update in this issue?
Thanks!

**Comment by LoranKloeze** [comment]
I found a way to subscribe to presence updates but the server doesn't react on that subscription. It's still on my list

**Comment by karopass** [comment]
Hi!
I have tried below code but I think its not worth. There no any changes in presence after subscribe via below codes.
`Store.Wap.subscribePresence(919400000000+ '@c.us').then(function(r){ console.log(r)})`
Thanks

**Comment by karopass** [comment]
@LoranKloeze 
I think below codes are removing subscription. If we prevent to run it than may be We can run it long time till We refresh.
`clearAllPresence: function() {
                this.forEach(function(e) {
                    e.reset(),
                    e.set({
                        stale: !0,
                        isSubscribed: !1
                    })
                })
            },`

**Comment by cijo7** [comment]
@LoranKloeze Any updates?

**Comment by LoranKloeze** [comment]
@karopass, you don't get presence updates from numbers that aren't in your contact list. WA has changed this. A few months ago you could get presence updates from all numbers but not anymore

**Comment by karopass** [comment]
@LoranKloeze Yes I know it but its still not get Presence update if number is in my contact list but have never send message to that contacts. There no any hope about run like before?
Thanks

**Comment by LoranKloeze** [comment]
Nope, I don't think so. I'll remove the references to the online statuses in the code and the readme.

**Comment by cijo7** [comment]
There is a new parameter called stale. The presence are not updated when stale is true. But works fine if stale is false. But manually setting it to false doesn't work.

**Comment by eandreini** [comment]
There is an app for iPhone named NETWA that collects presence data of up to 10 numbers. The app connect to their server and update information. I'm quite sure they use socket flow information of presence considering they have 1 s resolution. It stopped working begin of may. Then they add possibility of only 1 number per user, then 2, 4 and now 10 again. So they have managed how to solve the problem.
And I have tested they don't send any message to numbers you monitor. So, there should be the way to get it.

**Comment by LoranKloeze** [comment]
This means someone has to put in a lot of time to reverse engineer the undocumented API. I'm a little busy with commercial projects. Maybe later this year :)

**Comment by LoranKloeze** [comment]
I'm gonna close this. WhatsApp has fixed the privacy issue we we're using. 
This will never work again. I'm sorry. 
**Please don't open this issue again.** 
Thanks.
