### ISSUE TITLE
Store object vanished by WhatsApp

### ISSUE THREAD

**Issue by karopass** [LoranKloeze/WhatsAllApp#15]
Hi!
WhatsApp have removed Store object? Its not showing anymore!
Let me know if same got by others!
Thanks

**Comment by pakuteyeng** [comment]
yess, u allright. same for me after i refresh the page

**Comment by yahyaanwar** [comment]
my project failed because of it ;(

**Comment by karopass** [comment]
@LoranKloeze 
Please do something! We are waiting for you to save our projects!
Please make premium support etc for it but make it working!
Thanks

**Comment by LoranKloeze** [comment]
WhatsApp has reworked a lot of stuff. It looks like I can get it to work but at this moment I don't have the time to do this for free. It may take a day or what to find out what to do and I can't guarantee anything so sending me money to 'fix' it is a bad idea since there are no guarantees from my end in terms of a timeline or a real fix. It's a matter of trying.

My hourly fee is € 90,-/hour. Are you guys okay with sending me € 720 for only research? I don't think so ;-)

Once I have the time, I'll take a look at it.

**Comment by karopass** [comment]
Hi!
Thanks for reply! I think We all should contribute via donation! I understand that here only @LoranKloeze doing all task and We all are taking benefit of it using in our projects. Its really hard for me to send this amount alone. I know no one will send it. I think @LoranKloeze You should start provide premium benefit to people who subscribe via donate like this. https://github.com/mgp25/Instagram-API/issues/1231 I don't know my idea is bad or right but I really need this. Please think and do something so We can get it working again. No matter its publicly available or private via subscription method.
Thanks a lot!

**Comment by QuickEagle** [comment]
Ich schließe mich dem an.

**Comment by LoranKloeze** [comment]
Very much appreciated gesture! :)

It's just that I can't promise any results so it doesn't feel right to ask for money at this point but who knows. Let me think about it. I have to reverse engineer the 'closed' API of WhatsApp. 

Let's see how much everybody wants to chip in :)

Bitcoin address: 1DTqXrfnQrUutj7bGtKuhc5hP2DhZLXMC8

[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=PHVYMCEVZNLPA)

**Comment by LoranKloeze** [comment]
Take a look at the README change: https://github.com/LoranKloeze/WhatsAllApp/blob/master/README.md

**Comment by mertxkaan** [comment]
Hi Loran, 
I just stop by for a message and want to thank you for the code you provide. For some time, I had used it (in fact I kept modifying the basic code too many times, so at last it had been an automaton:) for my personal need and it had been a timesaver to me. On that way this old man have learned javascript for that:) Thank you.

And the other guys;
The same functions still there _dynamically_, as I see it; but **not** easy to find. It needs hard work really;)

Take care

**Comment by karopass** [comment]
Hi!
I am able to use Store and Store.Wap with below codes.
but its still have same issue as 
https://github.com/LoranKloeze/WhatsAllApp/issues/13

I am pasting this code here which can help to solve issue.

```
window.Store = {}; webpackJsonp([], { "bcihgfbdeb": (x, y, z) => window.Store = z('"bcihgfbdeb"') }, "bcihgfbdeb");
window.Store = {}; webpackJsonp([], { "dgfhfgbdeb": (x, y, z) => window.Store.Wap = z('"dgfhfgbdeb"') }, "dgfhfgbdeb");
```
Thanks

**Comment by LoranKloeze** [comment]
Thx for your contribution. This works at the moment but I'm not sure this is a very future-proof solution. Those strings are generated by webpack, I think. So each time WA updates their code base, chances are that those strings are regenerated.

**Comment by karopass** [comment]
@LoranKloeze You are right!
I hope You will find something Good and will make it working again!
Thank You so much!

**Comment by ricardoperovano** [comment]
@karopass it's very helpfull. it can brings back the project for a while. 
Did you find a way to send message using this approach ?
Thanks

**Comment by karopass** [comment]
@ricardoperovano 
I have never tried to send messages etc.
If I find the way, I will update here
Thanks

**Comment by LoranKloeze** [comment]
Give it a try people. I installed one hell of an ugly hack to find out what the dynamic function names are. Let's hope it keeps working...

**Comment by c0b41** [comment]
@LoranKloeze or use this  [#L239-L253](https://github.com/lieuwex/whapp-irc/blob/master/whapp/whapp.go#L239-L253)

**Comment by ZetDeveloper** [comment]
this code fixes many things

`
`if (window.Store === undefined) {
    webpackJsonp([], {"bcihgfbdeb": (x, y, z) => window.Store = z('"bcihgfbdeb"')}, "bcihgfbdeb");
    webpackJsonp([], {"iaeeehaci": (x, y, z) => window.Store.Wap = z('"iaeeehaci"')}, "iaeeehaci");
}`
`

**Comment by LoranKloeze** [comment]
First, it's already been fixed. Check the latest commits.
Second, don't post fixes with constant strings in them like these. Webpacker will change them and then the fix isn't a fix anymore. 
Closing this. If the code still doesn't work, open up this issue. :)

**Comment by LoranKloeze** [comment]
@c0b41, thx for you contribution. The problem with that code is that those webpack strings are constant that may or may not change in the near or distant future.
