### ISSUE TITLE
exception on ui.js

### ISSUE THREAD

**Issue by michelelaporta** [LoranKloeze/WhatsAllApp#16]
Hi
I'm testing the lastest push. I'm using:
Chromium
Versione 66.0.3359.181 (Build ufficiale) Built on Ubuntu , running on Ubuntu 16.04 (a 64 bit)

				305:var res = regExDynNameStore.exec(js_src);
				306:var funcName = res[1];
variable res is null.

Uncaught (in promise) TypeError: Cannot read property '1' of null
    at readMore (ui.js:306)
readMore @ ui.js:306
Promise.then (async)
(anonymous) @ ui.js:317
(anonymous) @ ui.js:344
 
Any help is appreciated

Michele

**Comment by michelelaporta** [comment]
I didn't enable desktop notification. Sorry it's working now.

**Comment by michelelaporta** [comment]
It's working on win7 with google chrome 67.0.3396.62(x64). Still same problem on :
Chromium
Versione 66.0.3359.181 (Build ufficiale) Built on Ubuntu , running on Ubuntu 16.04 (a 64 bit)

**Comment by pakuteyeng** [comment]
this is Done or NOT ? 

variable res is null.
Uncaught (in promise) TypeError: Cannot read property '1' of null

(on WIn8 using chrome 67.0.3396.62(x64).

**Comment by LoranKloeze** [comment]
Should work, ctrl+f5 and make sure you use the latest in the master branch.

**Comment by michelelaporta** [comment]
it's working now
