### ISSUE TITLE
Green Button does nothing

### ISSUE THREAD

**Issue by enduser83** [LoranKloeze/WhatsAllApp#17]
Hello there,

im a total noob with this app and I just downloaded it.
The install looks fine to me but when I click on the green button nothing happens...(I can only right click it)  
I already disabled all extensions beside this one, updated my chrome and the devmode is on.
What am I missing or doing wrong?

I hope someone can help me.
Thanks
a enduser

**Comment by pakuteyeng** [comment]
yess. same problem. please...

**Comment by LoranKloeze** [comment]
Which browsers? (Chrome/FF/IE + version)

**Comment by enduser83** [comment]
Its Chrome Version 67.0.3396.62 on Win7x64 for me.

**Comment by LoranKloeze** [comment]
Thx, can you tell me what's in the console (F12) once you click the green button?

**Comment by pakuteyeng** [comment]
I use chrome and opera browser. Same error on console

**Comment by LoranKloeze** [comment]
Sounds like this one: https://github.com/LoranKloeze/WhatsAllApp/issues/16

**Comment by enduser83** [comment]
it said

Uncaught (in promise) TypeError: Cannot read property '1' of null
    at readMore (ui.js:306)
mmg-fna.whatsapp.net/d/f/At5SHh1k2-BFfTQpUwzxx-DQuYT0_3XCafMhRCBONvRD.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/ArmTDA3cXDl2KxE0IAv4ifhFgOV2vDrGLdUXXVds-XNR.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/Ai_xGAzufopzuD4tlwD5hKUD2wlRD8Wim7PIohfdUbwB.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/AigPJQBvm1-MxI6O1c-37nEKJw3tVWgcO30LYdHRr0ez.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/AnTyOaFOWhVc5-I3HMg9hzk3w707D3wMTS1Th-AZmmxq.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/AoKl_YmTIa638zdswVa67cGPG1ZXtPNyx6rG1T4q0FHN.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/AhEJYkO3VPlG9YfAcD0DgNiJ5ZPXxz1Wg8DTSsbm73yH.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/AkCjbO8nd1NRUlq_nS391F_lpBqQpNYv41wtE3dHJ02t.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/AhazhZ07-mCWYcNzr5uVWsNj6g0ue9EuM0ddqFmUWGmh.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/AvPCLZqSz6sHiKZXXIRSX9fKIcksVhuKzGPlBVUbgRQ7.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/AimkrTf85H-DinvlbSEX-PwHyqgHJjO45uWSICqNhEv4.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/AniJ8iyqlJoCDfX6x50QrbLj00sL5u5-nrqM9Wq0MgND.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/AsqZbD10uFM_whLRF-Vp2B3lJJAfiQQbLLYxNDAwUhDY.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/AmhHJp3M-6MFjqCoR3RmfpZBzScFoD6hERhm9ImZ1Rv8.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/AsPJvW0zLiOQzXy9rk7UThDPbcAB_BbvI350JsdqBIq5.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/AjtaJiqRP9_ERnvMBIKSKg1F4ZTiLdG5ERCUrXTsmqRt.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/Aure5R84K-M0afQxj1C9Xq4ndl6s3AFPzVKeE2rsyHjS.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/ApuXCp1HlyDud-nw1CK7bmqdi3KlBCvvwVbO-hU9FWxA.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/Al_Wbs-gu_1hM4YqXq-VGyBtB8j_esXaG5uS9S5wyaKR.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/ApK4_Rt8lF9Vb_e44PmdDDXQigjequNQHqK2kiXSHSt_.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/Aoal4cxnYrn9NPFn1a-Z0txf9pb4gQPCMzAtIkBdzfAV.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/Ar4AdaXxQVvK-TKgpucRjxLX3jxpliXCVJSgK02b-r0W.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/AjSFcKSMht_-mOvDDVLnHG5CRXi1c4r_A3vzSKgNdaTJ.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/AgsxfficSz9HplZ8H5rK3gJiAdJOg1JZKm87Dd_2wdPY.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/Aq57mrELaKBIoduEbjkZHjCezbkT1cclTK_hL7xQxlAt.enc:1 Failed to load resource: the server responded with a status of 404 ()
mmg-fna.whatsapp.net/d/f/AkEjF-p6JwSCqo4rRBO81y5QBAFAXkGUpXorcAEjMtGn.enc:1 Failed to load resource: the server responded with a status of 404 ()

**Comment by pakuteyeng** [comment]
with this Chrome Version 67.0.3396.62 still error, the green button not display

**Comment by LoranKloeze** [comment]
I'm gonna take a look at it. Obviously there is something wrong :)

**Comment by pakuteyeng** [comment]
yes thank you for your attention

**Comment by enduser83** [comment]
Thank you for your support :)

**Comment by LoranKloeze** [comment]
Turns out that I tested only ui.js. But this is a Chrome extension... stupido me.
Anyway, the script started iterating <script> tags before React finished up the DOM and that caused the errors. 

Give it a try please!

**Comment by LoranKloeze** [comment]
That has something to do with the phone numbers. I get the same results (429) for the numbers you entered. Other numbers do work.

**Comment by enduser83** [comment]
It worked :D
Thank you

**Comment by LoranKloeze** [comment]
Anytime! :)

**Comment by thunderbird142** [comment]
The extension is not working for me. I get the errors below. I am a complete noob and a sad one at that!

ui.js:formatted:438 Uncaught (in promise) TypeError: Cannot read property '1' of null
    at readMore (ui.js:formatted:438)
readMore @ ui.js:formatted:438
NodeParser.js:163 Uncaught (in promise) Error: invalid token 151
    at NodeParser.getToken (NodeParser.js:163)
    at NodeParser.readString (NodeParser.js:124)
    at NodeParser.readAttributes (NodeParser.js:177)
    at NodeParser.readNode (NodeParser.js:85)
    at NodeParser.readList (NodeParser.js:185)
    at NodeParser.readNode (NodeParser.js:91)
    at Main.js:71
NodeParser.getToken @ NodeParser.js:163
NodeParser.readString @ NodeParser.js:124
NodeParser.readAttributes @ NodeParser.js:177
NodeParser.readNode @ NodeParser.js:85
NodeParser.readList @ NodeParser.js:185
NodeParser.readNode @ NodeParser.js:91
(anonymous) @ Main.js:71
Main.js:567 Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at getCSSRule (chrome-extension://dmojkdggbdjlhgmakakajjbbdibkjkgj/core/Main.js:567:39)
    at HTMLDocument.<anonymous> (chrome-extension://dmojkdggbdjlhgmakakajjbbdibkjkgj/core/Main.js:89:3)
getCSSRule @ Main.js:567
(anonymous) @ Main.js:89
NodeParser.js:163 Uncaught (in promise) Error: invalid token 151
    at NodeParser.getToken (NodeParser.js:163)
    at NodeParser.readString (NodeParser.js:124)
    at NodeParser.readAttributes (NodeParser.js:177)
    at NodeParser.readNode (NodeParser.js:85)
    at NodeParser.readList (NodeParser.js:185)
    at NodeParser.readNode (NodeParser.js:91)
    at Main.js:71
NodeParser.getToken @ NodeParser.js:163
NodeParser.readString @ NodeParser.js:124
NodeParser.readAttributes @ NodeParser.js:177
NodeParser.readNode @ NodeParser.js:85
NodeParser.readList @ NodeParser.js:185
NodeParser.readNode @ NodeParser.js:91
(anonymous) @ Main.js:71
Promise.then (async)
wsHook.after @ Main.js:66
(anonymous) @ WebScoketInterception.js:88

**Comment by LoranKloeze** [comment]
@thunderbird142 Please don't comment in closed a issue unless the issue is present again. I advise you to create a new issue so other people can see it and help you with it.

**Comment by thunderbird142** [comment]
Hi
I download the zip file and tried to unpack the extension in to Chrome. I got a message that the manifest file is missing or corrupted. Please can you help me to get the UI working?

**Comment by LoranKloeze** [comment]
@thunderbird142 Please don't comment in closed a issue unless the issue is present again. I advise you to create a new issue so other people can see it and help you with it.
