### ISSUE TITLE
Feature Request: Checkbox for: entries with image only

### ISSUE THREAD

**Issue by gr4ssi** [LoranKloeze/WhatsAllApp#2]
:-)

I'd suggest a feature: Checkbox for: entries with image only
or: with genuine status text only.

**Comment by LoranKloeze** [comment]
I'll expand it since it is related: only show numbers that are backed by an actual WhatsApp account. As far as I can tell that information can be extracted from the API.

**Comment by LoranKloeze** [comment]
I've implemented this. Can you please take a look a at it?
![image](https://user-images.githubusercontent.com/12978070/41593055-0c812094-73bf-11e8-9275-acf803fbe611.png)

**Comment by LoranKloeze** [comment]
If there are any bugs, please open a new issue :)
