### ISSUE TITLE
Plugin only loads placeholders and exits

### ISSUE THREAD

**Issue by layerviii** [LoranKloeze/WhatsAllApp#23]
Plugin has ran a few times, it comes back with all the numbers some show 'Hi Im using WhatsApp messages' but the tool cyclically filters through all of the preloaded image placeholders removing them one by one as time goes by eventually leaving a blank screen. No positive matches at all. I have tried a few ranges including numbers that I know are valid and public.

**Comment by muskw** [comment]
Download the latest code from `master`. Reinstall the extension. 

Are you still facing the issue? Mention your browser & OS.

**Comment by layerviii** [comment]
Have conducted the above but now when I click the green extension button I
get nothing at all.

Browser Chrome latest version
OS - Windows 10pro 64

**Comment by LoranKloeze** [comment]
Latest Chrome on Win10 should work. Download the correct version using these instructions: https://github.com/LoranKloeze/WhatsAllApp/issues/27#issuecomment-412271640
