### ISSUE TITLE
Notification Sound

### ISSUE THREAD

**Issue by Trjctry** [LoranKloeze/WhatsAllApp#25]
Hey. I'd like to add notification sound when someone comes online. 

> var audio = new Audio('notification.mp3');
> audio.play();

I couldn't figure out where to add these lines ni ui.js. When I add it it says "audio not defined" in console.
Can anyone enlighten me please?

**Comment by muskw** [comment]
I'm not sure how the audio plays. So, I'd suggest you have a new .js to try that part out. Once you've figured that out, here are the positions:

1. Add the `var audio = new Audio('notification.mp3` part after Ln 374. ie after `window.setInterval(function() {`

2. Add the `audio.play();` part after Ln 387. ie after `console.log(id + ' is online)`
