### ISSUE TITLE
there is nothng to pack on google chrome

### ISSUE THREAD

**Issue by gitdkm1** [LoranKloeze/WhatsAllApp#26]
I'm trying to install the WhatsAllApp extension using the developer mode in chrome. I am not able to do so as it finds nothing to attach.

I have downloaded the zip and followed the instructions. All I see is 2 png files and one license, one readme and three .js files and a folder which contains two more .js files. Chrome shows none as being loadable/packable.

I am using ubuntu 16.04 and I have sudo access which I confirmed by using sudo -v and got no error.

**Comment by muskw** [comment]
1. Extract the zip.
2. Go to chrome://extensions and choose to "Load Unpacked".
3. Go to the directory where you have extracted the zip. Don't go inside the 'lib' directory though. Select open.
