### ISSUE TITLE
green button disappeared

### ISSUE THREAD

**Issue by cgwb** [LoranKloeze/WhatsAllApp#27]
while loading whatsallapp, following error appears: 
Uncaught (in promise) TypeError: Cannot read property '1' of null
    at readMore (ui.js:453)

452 var res = regExDynNameStore.exec(js_src);
453 var funcName = res[1];

using chrome 68.0.3440.106 on a mac.

seems connected to #16 & #17 

cheers

**Comment by Trjctry** [comment]
I have the same issue right now. It was there like half an hour ago.

**Comment by muskw** [comment]
I'm facing the same since around 14 hours now.

Chromium Version 68.0.3440.75 (Official Build) & Chrome Version 68.0.3440.84 (Official Build), running on Ubuntu 18.04 (64-bit)

As per Console Logs, "Store" is created and it fails during "Store WAP" creation.

**Comment by QuickEagle** [comment]
Guten morgen Loran,

bei mir fehlt seit heute morgen auch der grüne Knopf.

Diese Fehlermeldung wird angezeigt. 

" ui.js:453 Uncaught (in promise) TypeError: Cannot read property '1' of null
    at readMore (ui.js:453)"

Was habe ich falsch gemacht? 

Dankbar für jeden Hinweis

**Comment by muskw** [comment]
I am a school student. $25=₹1730+. My monthly allowance is ₹1500.   :'(
Loran, I understand your situation too.

**Comment by muskw** [comment]
Loran, I have found the fix. But, I won't upload it here so that those who can donate get a chance to do so. Have emailed you what I did.  ;-)

**Comment by ahmtxonly** [comment]
@muskw you can help me ?

**Comment by cgwb** [comment]
im pretty interested in learning .js better & since i´m a school student i don´t have the money to send :/ sry @LoranKloeze,
so maybe you could email me a hint @muskw? wouldbe highly appreciated :)

**Comment by AdamSmith1020** [comment]
I have green button but nothing happens when i click on it.

No errors in console too :(

**Comment by AdamSmith1020** [comment]
@LoranKloeze Please check your email :)

**Comment by AdamSmith1020** [comment]
@LoranKloeze Please check your email again. Done as required. Thanks :)

**Comment by LoranKloeze** [comment]
You've got mail, thank you for your donation! :)

**Comment by muskw** [comment]
It can be fixed by changing thile line:
`var regExDynNameStore = /Wap:n\('"(\w+)"'\)/;`
to:
`var regExDynNameStore = /Wap:[a-z]\('"(\w+)"'\)/;`

P.S. It fixes only the current issues (#27); check the console log in case it's still failing due to something else!  ;-)

I hope @LoranKloeze wouldn't mind me giving the fix I had found.

cc: @ahmtxonly, @cgwb

**Comment by LoranKloeze** [comment]
I pushed the latest fixes. Closing this for now.
