### ISSUE TITLE
WhatsAllApp Pro Features

### ISSUE THREAD

**Issue by karopass** [LoranKloeze/WhatsAllApp#30]
Hi!
I am happy to hear that You are launching pro version of API. Let us know which functions will be available in it so We can decide to subscribe it.
Thanks

**Comment by LoranKloeze** [comment]
Hi,
Thx for your mail!

Some of the features I intent to add are:

  *   Sending results to your own server
  *   Making the extension act as a satellite so you can use a C&C server to control the extension
  *   Much improved UI using React
  *   Persistence of numbers and results in the browser
  *   Maybe sending/receiving messages

It all depends very much on WhatsApp’s own API.

But that the gist of it for now :)

Br Loran

**Comment by AdamSmith1020** [comment]
Thanks @LoranKloeze for the great work. 
I do not use WhatsAllApp for commercial purpose. I code just as my hobby (do not have IT background) and found your app very interesting.
I look forward to the Pro version :)

**Comment by LoranKloeze** [comment]
I'll get back to you all at later moment in time about the pro version.
