### ISSUE TITLE
Nothing happens when you click on the green 'start indexer' button - WhatsAllApp

### ISSUE THREAD

**Issue by AdamSmith1020** [LoranKloeze/WhatsAllApp#31]
Hello @LoranKloeze 

WhatsAllApp was all working fine until yesterday but since morning, I observed that when you click on the green 'start indexer' button, nothing happens.

Also, no error pops up in the console so not sure whats wrong.

Would you be able to help resolving this issue please?

Thanks in advance :)

**Comment by AdamSmith1020** [comment]
@LoranKloeze Please check your email :)

**Comment by LoranKloeze** [comment]
Hi Adam, thx for reporting the issue. Please check https://github.com/LoranKloeze/WhatsAllApp/issues/27#issuecomment-412271640 :)

**Comment by AdamSmith1020** [comment]
Hi Loran,

Thanks, I got your point :)

Please find attached the receipt for donation.

Could I now have the solution for 'start indexer' button issue, please? :)

Kind regards,

Adam

**Comment by AdamSmith1020** [comment]
Done as req Loran :). Please check ur email again. Thanks :)

**Comment by LoranKloeze** [comment]
Hi,

Glad you got the point ;)

You can download the newest repo here: https://www.dropbox.com/s/rqkl2avfq27d8dx/WhatsAllApp3.zip?dl=0

Thank you for you support and trust! :)

Br Loran

**Comment by AdamSmith1020** [comment]
Thank you :)
