### ISSUE TITLE
[Feature Request] Visualize online activity of a user

### ISSUE THREAD

**Issue by pussfacestalk** [LoranKloeze/WhatsAllApp#33]
Hello Loran,

I have seen this interesting graph in your [blog post](https://www.lorankloeze.nl/2017/05/07/collecting-huge-amounts-of-data-with-whatsapp/). Is it possible to generate a visual representation of specific users' (have already initiated a chat with) past activity while extension is running? Im trying to figure out whether this function is already in the code or have to manually perform it? If so how?
![image](https://user-images.githubusercontent.com/23431570/44987440-d8b46b00-afa4-11e8-8ac4-336bd88e8bcf.png)
At the very least, have timestamps for the logged events in console like below which I have taken from [here](https://stackoverflow.com/a/18818533/7850985)?

`[15:09:47.746] staging server listening on port 3000`

Please implement this functionality in the future builds if possible.

Thank you.

**Comment by delcantao** [comment]
Maybe the original code permit get it directly from server, without having to start a chat before, take a look this function from original WhatsApp JS:

![image](https://user-images.githubusercontent.com/19311485/48924486-0623fd00-eea0-11e8-8fe8-bfae0ef12e79.png)

I don't know how to use it but maybe you guys know
