### ISSUE TITLE
Where is the code of the previous WhatsAllApp?

### ISSUE THREAD

**Issue by LoranKloeze** [LoranKloeze/WhatsAllApp#35]
Some people wonder where the old code went. It's not gone :)

**Comment by LoranKloeze** [comment]
I've tagged the last commit before starting the overhaul. You can find it here: https://github.com/LoranKloeze/WhatsAllApp/tree/old

**Comment by Trjctry** [comment]
In the old code, we could see the activity on console. Can we still see it somewhere? Or it only shows last seen?

**Comment by AdamSmith1020** [comment]
Hi Loran,

The old code for Whatappall stopped working again today. Do you know why? I have been using it while waiting for Whatappall pro version. Please help. Thanks.
