### ISSUE TITLE
Uncaught error and manifest file not working

### ISSUE THREAD

**Issue by thunderbird142** [LoranKloeze/WhatsAllApp#36]
Hi Loran

The extension is not working for me. I get the errors below. I am a complete noob and a sad one at that!

ui.js:formatted:438 Uncaught (in promise) TypeError: Cannot read property '1' of null
at readMore (ui.js:formatted:438)
readMore @ ui.js:formatted:438
NodeParser.js:163 Uncaught (in promise) Error: invalid token 151
at NodeParser.getToken (NodeParser.js:163)
at NodeParser.readString (NodeParser.js:124)
at NodeParser.readAttributes (NodeParser.js:177)
at NodeParser.readNode (NodeParser.js:85)
at NodeParser.readList (NodeParser.js:185)
at NodeParser.readNode (NodeParser.js:91)
at Main.js:71
NodeParser.getToken @ NodeParser.js:163
NodeParser.readString @ NodeParser.js:124
NodeParser.readAttributes @ NodeParser.js:177
NodeParser.readNode @ NodeParser.js:85
NodeParser.readList @ NodeParser.js:185
NodeParser.readNode @ NodeParser.js:91
(anonymous) @ Main.js:71
Main.js:567 Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
at getCSSRule (chrome-extension://dmojkdggbdjlhgmakakajjbbdibkjkgj/core/Main.js:567:39)
at HTMLDocument. (chrome-extension://dmojkdggbdjlhgmakakajjbbdibkjkgj/core/Main.js:89:3)
getCSSRule @ Main.js:567
(anonymous) @ Main.js:89
NodeParser.js:163 Uncaught (in promise) Error: invalid token 151
at NodeParser.getToken (NodeParser.js:163)
at NodeParser.readString (NodeParser.js:124)
at NodeParser.readAttributes (NodeParser.js:177)
at NodeParser.readNode (NodeParser.js:85)
at NodeParser.readList (NodeParser.js:185)
at NodeParser.readNode (NodeParser.js:91)
at Main.js:71
NodeParser.getToken @ NodeParser.js:163
NodeParser.readString @ NodeParser.js:124
NodeParser.readAttributes @ NodeParser.js:177
NodeParser.readNode @ NodeParser.js:85
NodeParser.readList @ NodeParser.js:185
NodeParser.readNode @ NodeParser.js:91
(anonymous) @ Main.js:71
Promise.then (async)
wsHook.after @ Main.js:66
(anonymous) @ WebScoketInterception.js:88

Also I downloaded the zip file and tried to unpack it but got a error message saying that manifest file is missing.

Please help. Thanks so much.

**Comment by LoranKloeze** [comment]
Did you follow these steps?

1. Click 'clone or download' and choose to download the ZIP file
2. Extract the folder from the ZIP file
3. Open up chrome://extensions/
4. Enable developer mode at the top of the screen by clicking the slider
5. Click 'load unpacked extension'
6. Select the dist/ folder from step 2
7. The extension should appear at the top of the list
8. Refresh your WhatsApp web
9. An orange slider should appear at the top of the screen

**Please direct your attention to step 6 to make sure you point Chrome to the correct folder.**

**Comment by LoranKloeze** [comment]
Just tested it on Chrome 68/Win10 and it seems to work fine.
Where do you see that error? Can you make a screenshot? You can ctrl-c/v it in these comments.

**Comment by thunderbird142** [comment]
Hi Loran 
Chrome version is 68.0.3440.106.
I am getting the error below:

Failed to load extension
File
~\Downloads\WhatsAllApp-master (3)\WhatsAllApp-master
Error
Manifest file is missing or unreadable
Could not load manifest.

**Comment by LoranKloeze** [comment]
You have to select the /dist folder as it says in step 6.

**Comment by LoranKloeze** [comment]
You're welcome. Please check the FAQ at the README.md for these questions.

**Comment by thunderbird142** [comment]
Thanks so  much <3
