### ISSUE TITLE
Failed to load extension File... Error Manifest file is missing or unreadable

### ISSUE THREAD

**Issue by yarishyap** [LoranKloeze/WhatsAllApp#39]
Chrome:

Failed to load extension
File
~\OneDrive\Desktop\WhatsAllApp-master
Error
Manifest file is missing or unreadable
Could not load manifest.

**Comment by AdamSmith1020** [comment]
[https://github.com/LoranKloeze/WhatsAllApp/issues/36](url)

**Comment by AdamSmith1020** [comment]
#36
