### ISSUE TITLE
Api URLs

### ISSUE THREAD

**Issue by kw005** [LoranKloeze/WhatsAllApp#4]
How I can separately access the API URL, e.g. the first one in order to curl it for example? I don't see that so far.

**Comment by LoranKloeze** [comment]
I'm sorry, that is really outside the scope of this extension. For starters, this API moves calls to the WebSocket. As far as I know, curl doesn't support sending/receiving WebSocket packets. And the API abstracts all the complex logic of sending and receiving including authentication and encryption. I can't help you with that at the moment.
