### ISSUE TITLE
Add database connection

### ISSUE THREAD

**Issue by LorenzNickel** [LoranKloeze/WhatsAllApp#43]
Hello,

It'd be really cool if there was a possibillity to save the last-seen data to for example a MySQL Database so you can for example show the data on a website. And if something like this https://github.com/LoranKloeze/WhatsAllApp/issues/33 should be implemented, you could again add an option to save this data to an user-picked database so you can use it for other things.

Have a good day
Lorenz

**Comment by LoranKloeze** [comment]
Thx for your feature request!

**Comment by rtenicewaserv** [comment]
I expected this to be somehow like Maikel Zweerinks now unsupported work.
It was cool to use it with a database on the rpi (https://gitlab.maikel.pro/maikeldus/WhatsSpy-Public/wikis/home)
