### ISSUE TITLE
"whatsallapp-root" element not found

### ISSUE THREAD

**Issue by lenke182** [LoranKloeze/WhatsAllApp#46]
While using the current version, the whatsallapp-view and button is not visible and chrome throws the following error, because the root-element isn't correctly injected:
`Uncaught TypeError: Cannot read property 'getAttribute' of null`
by calling:
`document.getElementById("whatsallapp-root").getAttribute("data-extension-id");`
somewhere in the bundle.js

Any idea why I isn't correctly injected?

Chrome: 69.0.3497.100
WhatsAllApp: Current dist build

**Comment by LoranKloeze** [comment]
Please check https://github.com/LoranKloeze/WhatsAllApp/issues/104 😊
