### ISSUE TITLE
Chrome Notification for when a number comes online.

### ISSUE THREAD

**Issue by OyeBenny** [LoranKloeze/WhatsAllApp#47]
A chrome notification when online status changes.

**Comment by pussfacestalk** [comment]
> A chrome notification when online status changes.

Hey,
This [script](https://greasyfork.org/en/scripts/17410-whatsapp-online-notifier/code) is not by the same repo owner however it partly does what you have mentioned. The limitation is, it only works with only one chat at a time (one in focus). On the plus side, it still generates notification for the one chat in focus and additionally logs online times (time contact came online, not duration) in dev console n generates a beep :)

Furthermore;
for ios (jb): [OnlineNotify ](http://cydia.saurik.com/package/com.f0u4d.onlinenotify/)
android: [GBWhatsApp](http://www.gbmods.co/?p=19)

Hope it helps.
_Please feel free to edit/delete this reply if links to external sources are not allowed._

**Comment by SrMilton** [comment]
Good idea

**Comment by nityoday** [comment]
Thank you for your response

**Comment by muskw** [comment]
@OyeBenny To be frank, you'd go crazy. Even a single person while having a 1 hour conversation may go online/offline dozens of times. It would be better to write the log with timestamp instead. Save it to a file. Then do whatever analysis you want.

**Comment by nityoday** [comment]
@muskw Yes, we can make a minimum limit, that if a person comes online under 15 mins again, we won't get a notific .
Yes of course the LOG file is the accurate way we need to do it . Netwa again , has this notification and logging thing available ..

**Comment by rizwansoaib** [comment]
https://github.com/rizwansoaib/whatsapp-monitor
