### ISSUE TITLE
Version with different chosen numbers

### ISSUE THREAD

**Issue by MoritzRS** [LoranKloeze/WhatsAllApp#5]
Ok guys the problem is this: I'm in class 10 at school and we have to make a presentation about digital security and spying. WhatsAllApp would be perfect for this, but we aren't allowed to show random numbers. So what we need is a version of this extension where you don't index a range of numbers but 5 typed in numbers(where we can type in our own numbers for the presentation). I already tried to rewrite this script myself but I'm not that talented with javascript. Can anyone help me and my group? Oh and yes I already asked Mr. Kloeze and he said I should try it on Github because he doesn't have the time.

**Comment by gr4ssi** [comment]
Why don't you run it 5 times, each time with a single number. Just put the same number in both fields.
So you don't have to rewrite the code. :-)

**Comment by gr4ssi** [comment]
I tried to implement this, it seems to work:
https://gist.github.com/gr4ssi/e6f4288f5eff2154f7a54e16958e9dc9

Input your phone numbers in line 52.

**Comment by MoritzRS** [comment]
Thanks it worked great!
We'll use it in our presentation next week.
