### ISSUE TITLE
Online status mobile phone vs. whatsallapp

### ISSUE THREAD

**Issue by cgwb** [LoranKloeze/WhatsAllApp#51]
Comparing the last seen on my phone for a number and the whatsallapp last seen does differ sometimes for some minutes or last seen (mobile phone) shows a time, that whatsallapp has not noticed. (Changed the steps to 1 sec already). Has anyone else similar problems? And what could be the reasons for this? 
Thx in advance for your feedback :)

**Comment by muskw** [comment]
Your computer's connection must be dropping or maybe the WiFi goes in power-saving mode. Disable power-saving, and if possible use a wired connection for better results.
