### ISSUE TITLE
Usage instructions not working

### ISSUE THREAD

**Issue by cur0sity** [LoranKloeze/WhatsAllApp#55]
On Chrome Version 71.0.3578.80 (Official Build) (64-bit) and windows 10, I installed plugin successfully and enable it on the chrome browser as instructed. However I don't see any arrow to see options to key in phone numbers. I refreshed browser and restarted but no success. Appreciate any pointers to resolve this. 

Thanks

**Comment by LoranKloeze** [comment]
Please check https://github.com/LoranKloeze/WhatsAllApp/issues/104 😊
