### ISSUE TITLE
WLAPWAPStore.subscribePresence is not a function

### ISSUE THREAD

**Issue by MuditMathur96** [LoranKloeze/WhatsAllApp#58]
Working till 24-01-2019 suddenly started throwing errors about WLAPWAPStore.subscribePresence is not a function and stops working

**Comment by AdamSmith1020** [comment]
The older version of the program is still working fine.

https://github.com/LoranKloeze/WhatsAllApp/issues/35

**Comment by MuditMathur96** [comment]
Same issue with the older version.Still showing "WLAPWAPStore.subscribePresence is not a function"
in console

**Comment by MuditMathur96** [comment]
Thanks for the reply but still same issue with the older version its
showing "WLAPWAPStore.subscribePresence is not a function"  in console
after submitting phone numbers

**Comment by Lolek79** [comment]
Hello to all,

I think you get the error, if you clear your browser cache to get the latest appXXXX.js and app2XXXX.js from WA.
After that, the function grepFunctionNames(...) in ui.js of WhatsAllApp can't extract the functions any more.

**Comment by AdamSmith1020** [comment]
Yes, same issue. The old version of Whatsapp is also not working now. Solution please guys!

**Comment by LoranKloeze** [comment]
Hi people,

I'm gonna look into this asap!

Br Loran

**Comment by WorldWideCrow** [comment]
Hello Loran
  On 23/11/19 late afternoon I noticed that I have blocked users visible (Pic green) were allso the online status was displayed in Whatsapp web.
On mobile, the user was not displayed online.
I immediately felt selsam, besides, I could write that message, but the reception was not confirmed.

they screwed something that day
Maybe that helps you with error search

Kind regards
Crow

**Comment by LoranKloeze** [comment]
I think I fixed it. Could you guys please give it another try?

**Comment by MuditMathur96** [comment]
It's working now. Thanks....

**Comment by AdamSmith1020** [comment]
@LoranKloeze 

Hi Loran,

Just did a small contribution of 25 USD for your hard work and helping us out. Hope others will do as well.

I have a small req. While waiting for the pro version of Whatsallapp, I have been using the old version of the program where I see results in the console. 

After your recent update, I have tried to fix the old version but not getting success. Could you please also fix the old ui.js file or provide with the required code so that I am able to continue using the old version? Since you know the error, I assume this will be a small fix for you now.

Your help is very much appreciated :).

Thanks.

**Comment by AdamSmith1020** [comment]
All good Loran. I have fixed the old file myself.

Thanks you :)

**Comment by LoranKloeze** [comment]
> @LoranKloeze
> 
> Hi Loran,
> 
> Just did a small contribution of 25 USD for your hard work and helping us out. Hope others will do as well.
> 
> I have a small req. While waiting for the pro version of Whatsallapp, I have been using the old version of the program where I see results in the console.
> 
> After your recent update, I have tried to fix the old version but not getting success. Could you please also fix the old ui.js file or provide with the required code so that I am able to continue using the old version? Since you know the error, I assume this will be a small fix for you now.
> 
> Your help is very much appreciated :).
> 
> Thanks.

Thank you very much for your donation! :) :)
