### ISSUE TITLE
how to open the csv data it extracts?

### ISSUE THREAD

**Issue by MuditMathur96** [LoranKloeze/WhatsAllApp#59]
Please tell me how to use the csv file after extracting it

**Comment by LoranKloeze** [comment]
You can open it in Notepad or import it into Excel.

**Comment by AdamSmith1020** [comment]
1. Right click
2. Open with
3. Microsoft Excel

Cheers!

**Comment by MuditMathur96** [comment]
Thanks for the reply but i guess i addressed my issue in an incorrect way
,actually what i meant was that when i open it in excel it shows name
,status and [Object] in place of other data.

**Comment by LoranKloeze** [comment]
Can you post a few rows from the csv?

**Comment by MuditMathur96** [comment]
Here is an example

**Comment by LoranKloeze** [comment]
I don't see anything?
