### ISSUE TITLE
Slider disappears

### ISSUE THREAD

**Issue by DaanTacoSchool** [LoranKloeze/WhatsAllApp#61]
The orange slider disappears from the screen when either one 'search in list' or 'search in range'  buttons are pressed. Basically preventing the app from working. This problem occurred since the enable/disable button appeared in the toolbar.

**Comment by QuickEagle** [comment]
![fehler](https://user-images.githubusercontent.com/31067054/53472752-d53c0100-3a68-11e9-995a-9b3d75f98e56.JPG)
 Guten Morgen, ich habe seit heute folgernden Fehler, kann mir jemand helfen. Danke

**Comment by LoranKloeze** [comment]
@QuickEagle, please create a separate issue to determine if more people have the same issue

**Comment by MuditMathur96** [comment]
I am having the same issue since 28 feb .Please look into this issue

**Comment by LoranKloeze** [comment]
Check https://github.com/LoranKloeze/WhatsAllApp/issues/64#issuecomment-468918423
