### ISSUE TITLE
Fehlermeldung und  Orange ner Balken erscheint nicht mehr

### ISSUE THREAD

**Issue by QuickEagle** [LoranKloeze/WhatsAllApp#63]
Bei mir ist seit heute morgen diese Fehlermeldung aufgetreten und die Funktion ist nicht mehr da.!
Vielen Dank für Hilfe 

[fehler](https://user-images.githubusercontent.com/31067054/53514505-2deeb680-3ac8-11e9-9da9-d0d0ed04996e.JPG)

**Comment by LoranKloeze** [comment]
Check https://github.com/LoranKloeze/WhatsAllApp/issues/64#issuecomment-468918423
