### ISSUE TITLE
Whatsapp API change

### ISSUE THREAD

**Issue by julianoo** [LoranKloeze/WhatsAllApp#64]
Today, i noted that whatsapp has changed the API.
Before was two files app and app2, now they have three files app1, app2, app3.

**Comment by RoelWKramer** [comment]
I just discovered the same. Will try to have a look into it. But this is the exact error:
```
Wapp DOM is ready!
VM241:1 Fetch finished loading: GET "https://web.whatsapp.com/app.1c910a99b9a8ac567544.js".
(anonymous) @ VM241:1
(anonymous) @ WWapApi.js:45
D @ app.1c910a99b9a8ac567544.js:30
i @ app.1c910a99b9a8ac567544.js:29
initApi @ WWapApi.js:18
(anonymous) @ index.js:36
setInterval (async)
(anonymous) @ index.js:32
./src/index.js @ bundle.js:3547
__webpack_require__ @ bundle.js:20
(anonymous) @ bundle.js:84
(anonymous) @ bundle.js:87
WWapApi.js:59 Uncaught (in promise) TypeError: Cannot read property '1' of null
    at readMore (WWapApi.js:59)
```

**Comment by RoelWKramer** [comment]
That function seems to be in app3 now. I am cooking a PR.

**Comment by MuditMathur96** [comment]
I am having the same problem 'cannot read property  1 of null'.

**Comment by RoelWKramer** [comment]
PR: https://github.com/LoranKloeze/WhatsAllApp/pull/65

**Comment by LoranKloeze** [comment]
I have pushed a fix and reworked it a little because we only need to fetch one script from WA anymore at the moment.

Could you guys give it a try please?

@RoelWKramer, thank you for your PR anyway! :)

**Comment by MuditMathur96** [comment]
It's working now..Thanks

**Comment by RoelWKramer** [comment]
@LoranKloeze thanks!

Although your fix seems a bit more brittle. I think the splitting up in app1, app2, app3 is done semi-automatically at WhatsApp. Finding it only in app1.js might break again in the future.

I just use WWapApi.js in my personal project. So leaving my fix in there anyways. Ill donate a beer on app launch ;-)

**Comment by QuickEagle** [comment]
Hallo @LoranKloeze und vielen Dank Spende ist raus. Mach weiter so.

**Comment by LoranKloeze** [comment]
Please check https://github.com/LoranKloeze/WhatsAllApp/issues/104 😊
