### ISSUE TITLE
Online is back ?

### ISSUE THREAD

**Issue by smarteutech** [LoranKloeze/WhatsAllApp#66]
Hi!
I think other repo have solution of get online and offline without chat.
https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/578
I think it will help to improve this one.
Thanks

**Comment by AdamSmith1020** [comment]
Thanks, @smarteutech.

@LoranKloeze Hey Loran, when you have time, could you please check in the above-provided thread to see if we can get online status without a chat with the target number? 

I tried but as I am not great at coding, I am not able to get it to work.

Thanks.

**Comment by fcabi** [comment]
Hi,
I tried. This solution also uses store object and data not set in client. At the same time if i try to connect from phone, data come over websocket. Without chat getting online status is not possible.
Thanks..

**Comment by LoranKloeze** [comment]
Gonna close this. Checking online presence of unknown WA users is not possible. Are you sure it *is* possible? Send this repo a PR with a working fix. Only linking to other repo's is not gonna cut it :)
