### ISSUE TITLE
Failed to load resource: the server responded with a status of 429 (Too Many Requests)

### ISSUE THREAD

**Issue by jegue** [LoranKloeze/WhatsAllApp#7]
HELLO,  what is the best way of not getting erros 429?
thanks

**Comment by LoranKloeze** [comment]
Well, the answer is kind of lame but it's simply a matter of throttling the requests. Try to put some waiting time between the requests. I think the throttling algorithm is based on ip addresses. Using multiple ip addresses might do the trick. Yes, it's very cumbersome but hey, it's undocumented stuff 😉
