### ISSUE TITLE
Stopped working today

### ISSUE THREAD

**Issue by lucke76** [LoranKloeze/WhatsAllApp#71]
The extension was working great but today stopped working, chrome just give an aw snap when trying to open whatsapp web

**Comment by SKRy0** [comment]
There is an error: Stacktrace bundle.js:90 

[https://puu.sh/DyCOc/373bba62d2.png](url)

**Comment by lucke76** [comment]
Yes, i also noticed that error, i think that whatsapp has changed his api overnight

**Comment by LoranKloeze** [comment]
I am able to reproduce this error. Working on a fix.

**Comment by LoranKloeze** [comment]
Got it working again. WhatsApp changed their undocumented API.
As usual, I'm gonna publish the fix in 2 weeks. 

**I want the fix right now**
No problem! If you want to receive the fixed WhatsAllApp right away send me $25 via Paypal (https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=PHVYMCEVZNLPA) and you'll receive the fixed code by mail. You might not like it but 25 dollars is not a lot of money I think :)

Why I ask for money you ask? Check this: https://github.com/LoranKloeze/WhatsAllApp/issues/27#issuecomment-412271640

**Comment by tyren542** [comment]
Does your extension log and save all last seen/online to a txt/csv file, also for user with hidden last seen? (not only showing the last seen)

If the extension already has this functionality or you are thinking of implenting it in a short terme i will donate and support you with great pleasure.

**Comment by LoranKloeze** [comment]
The donation is meant for the fix, not for other features. Check the README for current features and please add feature requests in separate issues.

**Comment by nityoday** [comment]
You got an Aw, Snap ? I got normal whatsapp web working but no orange bar or line , which used to work till last few months I guess . @LoranKloeze will your fix also fix this or is this a different error ?

**Comment by LoranKloeze** [comment]
Yeah, the fix will probably take care of that problem.

**Comment by afalonso** [comment]
> Got it working again. WhatsApp changed their undocumented API.
> As usual, I'm gonna publish the fix in 2 weeks.
> 
> **I want the fix right now**
> No problem! If you want to receive the fixed WhatsAllApp right away send me $25 via Paypal (https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=PHVYMCEVZNLPA) and you'll receive the fixed code by mail. You might not like it but 25 dollars is not a lot of money I think :)
> 
> Why I ask for money you ask? Check this: [#27 (comment)](https://github.com/LoranKloeze/WhatsAllApp/issues/27#issuecomment-412271640)

Hi! Would it be necessary to send money for each fix?

Thanks.

**Comment by LoranKloeze** [comment]
It depends on the fix.

**Comment by delcantao** [comment]
Loran, I made the payment, could you make the fix available to me, please? Thank you

**Comment by LoranKloeze** [comment]
Thank you! I've sent you the link to the fixed repo.

**Comment by kurama98** [comment]
Hi are you going to release the fix tomorrow?

**Comment by LoranKloeze** [comment]
Fix is released
