### ISSUE TITLE
Last seen stuck at "never"

### ISSUE THREAD

**Issue by nityoday** [LoranKloeze/WhatsAllApp#73]
Today, the extension was working perfectly fine , until after a page refresh , last seen was never updated and is now stuck at "never" , even if people come and go online or offline .

**Comment by LoranKloeze** [comment]
Let's wait and see if other people experience this as well. Keep in mind that 'last seen' only updates if you ever had a chat session with the account before.

**Comment by kurama98** [comment]
for me i wouldn't say it is stuck at never. last seen is there but after refresh it shows back to never. so after every refresh i couldn't know when the last seen until the next last seen

**Comment by nityoday** [comment]
@LoranKloeze @kurama98 It's working back, thank you . Appreciate your support :)

**Comment by muskw** [comment]
The Last  Seen is stuck at "never" unless the chat is currently open in WhatsApp app or web. Using latest Chromium. The issue is there for those profile too with whom I have had chats.
