### ISSUE TITLE
Last Seen stuck at "Never"

### ISSUE THREAD

**Issue by muskw** [LoranKloeze/WhatsAllApp#75]
The Last Seen is stuck at "never" unless the chat is currently open in WhatsApp app or web. Using latest Chromium. The issue is there for those profile with whom I have had chats, and the chats have NOT been deleted  either.

CC:  @LoranKloeze

**Comment by Suleman-Elahi** [comment]
![image](https://user-images.githubusercontent.com/24384996/62037983-7692d300-b212-11e9-9f8a-91518cc208eb.png)

Same prob here. It never updates even if you have chat with the participant.

**Comment by grIskra** [comment]
No solution?
What is the code not working anymore?
