### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by fake281** [LoranKloeze/WhatsAllApp#80]
Unable to display slider, bundle.js:59 (anonymous function)

**Comment by WorldCrow** [comment]
Uncaught (in promise) TypeError: Cannot read property '1' of null
Kontext
https://web.whatsapp.com/
Stacktrace
bundle.js:59 (Anonyme Funktion
*/var r=Object.getOwnPropertySymbols,a=Object.prototype.hasOwnProperty,i=Object.prototype.propertyIsEnumerable;e.exports=function(){try{if(!Object.assign)return!1;var e=new ..................

**Comment by schwabochino** [comment]
Same here, no slider in my chrome.

**Comment by madalinamicu83** [comment]
same problem, the orange slider does not appear...
bundle.js:59 (anonymous function)

**Comment by Gerasptekaas** [comment]
Same problem @ bundle.js:59

**Comment by WorldCrow** [comment]
Same problem @ bundle.js:59

MFG

Heinz

 

Von: Gerasptekaas <notifications@github.com> 
Gesendet: Mittwoch, 2. Oktober 2019 16:38
An: LoranKloeze/WhatsAllApp <WhatsAllApp@noreply.github.com>
Cc: WorldCrow <worldwidecrow@gmail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [LoranKloeze/WhatsAllApp] Display error (#80)

 

Same problem @ bundle.js:59

**Comment by delcantao** [comment]
For those who are still having trouble getting the app to work, the API now has app.js and app2.js files again, you will need to develop a regular expression that finds the "begfaahgdb" function in app.js . I hard coded that. ¯\_(ツ)_/¯.
In app2.js i don't know what the function is, I only use the app.js functions.

**Comment by afalonso** [comment]
> begfaahgdb

How do you do that?

**Comment by MarvineGothic** [comment]
https://github.com/LoranKloeze/WhatsAllApp/pull/81

**Comment by ginevra2013** [comment]
> For those who are still having trouble getting the app to work, the API now has app.js and app2.js files again, you will need to develop a regular expression that finds the "begfaahgdb" function in app.js . I hard coded that. ¯_(ツ)_/¯.
> In app2.js i don't know what the function is, I only use the app.js functions.


You can send the update by email, if it works, thanks?

**Comment by Pjotter-Vilbis** [comment]
Same here, it's my first experience with Github and coding. WIll there be updates on the main code page?

**Comment by ohari5336** [comment]
if this error u got #84 
![image](https://user-images.githubusercontent.com/22674877/67297983-43f23100-f508-11e9-95b6-a4d0c2d2548a.png)

then see this #83 

and change these two files

![image](https://user-images.githubusercontent.com/22674877/67298313-b531e400-f508-11e9-8738-09010586972b.png)

and

![image](https://user-images.githubusercontent.com/22674877/67298367-c7ac1d80-f508-11e9-8bbc-d49015663017.png)

I think after the problem of this change solved

**Comment by Pjotter-Vilbis** [comment]
Hi,

I still get error:

bundle.js:59 GET https://web.whatsapp.com/undefined 404 (Not Found)
bundle.js:59 Uncaught (in promise) TypeError: Cannot read property '1' of nul at n (bundle.js:59)

Does this make sense?

Regards,
Peter de Vink
peter.devink@gmail.com

**Comment by ginevra2013** [comment]
You cannot send the file that is already working, to be replaced. Thank you

**Comment by WorldCrow** [comment]
bundle.js:59 Uncaught (in promise) TypeError: Cannot read property '1' of nul at n (bundle.js:59)

bundle.js: 59 Uncaught (in promise) TypeError: Can not read property '1' of nul at n (bundle.js: 59)

Hello, So with me the error is fixed, since last week everything is ok with me, the error does not appear and the display appears as usual

greetings
Crow

**Comment by ohari5336** [comment]
> You cannot send the file that is already working, to be replaced. Thank you

ya why not 

https://ohari5336.tk/admin/index.php?share/file&user=1&sid=2jrynIGT

**Comment by CoraatB3ware** [comment]
For me the error message bundle.js:59 does not appear anymore. However, the slider is still missing. Does somebody has any idea?

**Comment by CoraatB3ware** [comment]
@ohari5336: Thanks for your great work! The comlete package of you works.

**Comment by ohari5336** [comment]
thank I am happy for helping you and my code works.

**Comment by schwabochino** [comment]
@ohari5336 didn't work for me. No error... Can't see any slider in my chrome at web.whatsapp.com :(
![whatsappall](https://user-images.githubusercontent.com/28741994/68069945-badcc480-fd67-11e9-9eae-d95434e68d86.png)

**Comment by ohari5336** [comment]
if anyone wants the latest version of this file :
https://ohari5336.tk/admin/index.php?share/file&user=1&sid=2jrynIGT

then go hear :
https://github.com/ohari5336/WhatsAllApp-Mod/releases

**Comment by ohari5336** [comment]
Delete extension and download from here
https://github.com/ohari5336/WhatsAllApp-Mod/releases
then try.

#@R! ()M Batra

**Comment by schwabochino** [comment]
@ohari5336 last seen seems to be not working. Every Contact is shon by never... Any suggestions what is then reason for that?

**Comment by ohari5336** [comment]
first time/defaults its show never check with your another family no.

**Comment by schwabochino** [comment]
@ohari5336 can you help me again? Is there already a log that I can export manually or automatically? The current export shows only a string [object] [object] under Last_seen.
I didn't find a passage in the source code that deals with the export. I would like to adjust the code so that whenever someone comes online an append to a created csv is executed with the corresponding values of name, status, time

**Comment by ohari5336** [comment]
> @ohari5336 last seen seems to be not working. Any contact is show never... Any suggestions what is then reason for that?
> 
> ![fail1](https://user-images.githubusercontent.com/28741994/68070426-5bce7e00-fd6e-11e9-93e2-8d3bf72de266.PNG)
> ![fail2](https://user-images.githubusercontent.com/28741994/68070433-756fc580-fd6e-11e9-933e-e569bacde6dc.PNG)

this is solved ??

**Comment by schwabochino** [comment]
> 
> 
> > @ohari5336 last seen seems to be not working. Any contact is show never... Any suggestions what is then reason for that?
> > ![fail1](https://user-images.githubusercontent.com/28741994/68070426-5bce7e00-fd6e-11e9-93e2-8d3bf72de266.PNG)
> > ![fail2](https://user-images.githubusercontent.com/28741994/68070433-756fc580-fd6e-11e9-933e-e569bacde6dc.PNG)
> 
> this is solved ??

Yes it is.

**Comment by ohari5336** [comment]
> I would like to adjust the code so that whenever someone comes online an append to a created csv is executed with the corresponding values of name, status, time

I already working on this how-to log all-time data when I success I add hear u download from hear
https://github.com/ohari5336/WhatsAllApp-Mod/releases

**Comment by ginevra2013** [comment]
It doesn't work anymore from today

**Comment by ohari5336** [comment]
please remove and reinstall extension if any error show then sends hear.

**Comment by ginevra2013** [comment]
Now it works, sorry. Thanks

**Comment by ohari5336** [comment]
> Now it works, sorry. Thanks

wlcm

**Comment by LoranKloeze** [comment]
Please check https://github.com/LoranKloeze/WhatsAllApp/issues/104 😊
