### ISSUE TITLE
It shows the error "Uncaught (in promise) TypeError: Cannot read property '1' of null"

### ISSUE THREAD

**Issue by JintoAntony** [LoranKloeze/WhatsAllApp#82]
<img width="678" alt="Screenshot 2019-10-15 at 11 35 37 AM" src="https://user-images.githubusercontent.com/1184993/66804427-0dcd1400-ef40-11e9-81be-c541ade85a91.png">

**Comment by ricardoperovano** [comment]
I solved It, will make a pull request

**Comment by JintoAntony** [comment]
> I solved It, will make a pull request

Thanks. Waiting for that.

**Comment by JintoAntony** [comment]
Also, I want to ask you some thing.  There are many applications, that can track users online presence. For example, Whatslog. I want to know, how there are doing it. Is there any API available for this ?  I heard about some undocumented API of Whatsapp, but, never found a real one. Whatslog like applications are not using Whatsapp Web (I think). Then, how they are doing it ? 
If you can help me, it will be very helpful.

**Comment by ohari5336** [comment]
I have also seen this issue and i ask this #84
Now I solved this with this #83 solution change all two file then run 'npx webpack' and then all normal

**Comment by cp82x** [comment]
#83 solution did not fix the problem. I ran the solution and received the same error

**Comment by ExtReMLapin** [comment]
Can confirm, problem not fixed.

**Comment by LoranKloeze** [comment]
Please check https://github.com/LoranKloeze/WhatsAllApp/issues/104 😊
