### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by ohari5336** [LoranKloeze/WhatsAllApp#84]
I got this error

![image](https://user-images.githubusercontent.com/22674877/67067435-069e4400-f194-11e9-8072-a8fca94f6e1f.png)

and nothing do in whatsapp site

![image](https://user-images.githubusercontent.com/22674877/67067519-3e0cf080-f194-11e9-9b66-febbadfc53a1.png)

**Comment by ricardoperovano** [comment]
#83 see the fix here
