### ISSUE TITLE
Blocking someone will show "never" for last seen?

### ISSUE THREAD

**Issue by tonystaark** [LoranKloeze/WhatsAllApp#85]
"Last seen" stuck at "Never". Is it possible the person has blocked me that's y it is "never"?

**Comment by ohari5336** [comment]
no, if u are blocked then u not get status like this:
![image](https://user-images.githubusercontent.com/22674877/69561436-6083fc00-0fd3-11ea-81f9-7b2eec0a097a.png)
first no. block me and second no. not block


Troubleshooting:
first, reload remove your extension then readd
