### ISSUE TITLE
Extension Not Working

### ISSUE THREAD

**Issue by CarloG76** [LoranKloeze/WhatsAllApp#86]
As Today the extension Is not working.
Simply the Orange bar Is not showing.
Any suggestioni on workarounds to fix It?
![IMG_20191128_114518](https://user-images.githubusercontent.com/17903464/69799966-9512d600-11d4-11ea-8f07-c67b3c43e56f.jpg)

**Comment by ohari5336** [comment]
Please remove extension then readd

**Comment by CarloG76** [comment]
Hi. Done, still not working.
The error is always

**Comment by CarloG76** [comment]
Uncaught (in promise) TypeError: Cannot read property '1' of null

**Comment by ohari5336** [comment]
> Uncaught (in promise) TypeError: Cannot read property '1' of null

please send full error

**Comment by CarloG76** [comment]
It is the same error of issues #83. 
I updated the file with the two of the issue #83 solutions, but still nothing is working. 

So the steps : 

1- Uninstall extension 
2- go to folder 
3- copy the #83 solution codes to the speciified files 
4- re-installed extension 
5- refresh of whatsappweb page

Nothing happens.

**Comment by ohari5336** [comment]
after 3rd step important to rebuild code.
if u not now how rebuild then use this repo https://github.com/ohari5336/WhatsAllApp-Mod#whatsallapp-mod

**Comment by CarloG76** [comment]
Done and working.
thank you.
