### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by peg-leg** [LoranKloeze/WhatsAllApp#88]
I'm not getting the orange slider - this is a new install:
https://i.imgur.com/M7ZS2OD.png

Chrome Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by emptyfullniss** [comment]
Same here

**Comment by ohari5336** [comment]
hello please see #89

**Comment by rizwansoaib** [comment]
Same here
how to open popup as in README

**Comment by ohari5336** [comment]
popup and readme??

**Comment by emptyfullniss** [comment]
> hello please see #89

All working for a while now. I found mod 2 and everything was fixed. Thanks a lot!

**Comment by rizwansoaib** [comment]
> > hello please see #89
> 
> All working for a while now. I found mod 2 and everything was fixed. Thanks a lot!

there is no last commit in repo

How can i run? only popup community on off showing

**Comment by ohari5336** [comment]
> > > hello please see #89
> > 
> > 
> > All working for a while now. I found mod 2 and everything was fixed. Thanks a lot!
> 
> there is no last commit in repo
> 
> How can i run? only popup community on off showing

if you don't mind please try this https://github.com/ohari5336/WhatsAllApp-Mod

**Comment by rizwansoaib** [comment]
https://github.com/rizwansoaib/whatsapp-monitor

**Comment by LoranKloeze** [comment]
Please check https://github.com/LoranKloeze/WhatsAllApp/issues/104 😊
