### ISSUE TITLE
Error in bundle.js? 

### ISSUE THREAD

**Issue by peha2407** [LoranKloeze/WhatsAllApp#89]
![Bildschirmfoto 2019-12-20 um 14 51 19](https://user-images.githubusercontent.com/6813170/71259599-18899800-2339-11ea-901f-ed81a971fc10.png)
Hi Loran
Do you know anything about this error message? Will there be a patch for that?
I hold a workshop with high school students about privacy, and last year, this plugin was a very good help for me to warn the students before WhatsApp "sniffing".

**Comment by peha2407** [comment]
Ok, it's a sort of duplicate of #82, #86 and #88. But nevertheless it doesn't work here (macOS 10.13 (High Sierra), Chrome 79.0.3945.88)

**Comment by nityoday** [comment]
I am getting the same error

**Comment by ohari5336** [comment]
if you don't mind please try this https://github.com/ohari5336/WhatsAllApp-Mod

**Comment by ricardoperovano** [comment]
I have already posted a fix to this. Check it out #83

**Comment by peha2407** [comment]
@ricardoperovano 
> I have already posted a fix to this. Check it out #83
I am sorry, your fix didn't work for me. 
@ohari5336 's mod works. Unfortunately it isn't possible to see the status of people who are not chatting with me. But for my purpose, it will be enough ...

**Comment by ohari5336** [comment]
> @ricardoperovano
> 
> > I have already posted a fix to this. Check it out #83
> > I am sorry, your fix didn't work for me.
> > @ohari5336 's mod works. Unfortunately it isn't possible to see the status of people who are not chatting with me. But for my purpose, it will be enough ...

![image](https://user-images.githubusercontent.com/22674877/71760497-a5f5ec00-2ee4-11ea-8239-1ef2459703f1.png)

I enter 7 numbers in Listbox and start tracking

![image](https://user-images.githubusercontent.com/22674877/71760518-04bb6580-2ee5-11ea-81a3-265c90e2d991.png)

now you see I save only 5 numbers in my phone but I see all the data of the other 2 numbers.
it's possible if user set everyone

**Comment by nityoday** [comment]
> if you don't mind please try this https://github.com/ohari5336/WhatsAllApp-Mod

This works, thanks !!

**Comment by WilliamReed2004** [comment]
> I have already posted a fix to this. Check it out #83

Not working either!

**Comment by LoranKloeze** [comment]
Please check https://github.com/LoranKloeze/WhatsAllApp/issues/104 😊
