### ISSUE TITLE
Pushname

### ISSUE THREAD

**Issue by mreinders** [LoranKloeze/WhatsAllApp#9]
Hello Loran,

Is it possible to get the pushname (name of the WhatsApp-profile) underneath the phonenumber? The info tag (for example: Hello I'm using WhatsApp) can be seen, so I think it must be possible to get the name also. 

I've searched a lot within the WhatsApp-API, but I can't find a possible solution.

**Comment by LoranKloeze** [comment]
I don't think that's possible atm.
