### ISSUE TITLE
Stop working

### ISSUE THREAD

**Issue by julianoo** [LoranKloeze/WhatsAllApp#94]
The Whatsapp changed the API. Any ideas in how back to work again?

**Comment by RoelWKramer** [comment]
function names changed again

**Comment by rizwansoaib** [comment]
https://github.com/rizwansoaib/whatsapp-monitor

**Comment by LoranKloeze** [comment]
Please check https://github.com/LoranKloeze/WhatsAllApp/issues/104 😊
