### ISSUE TITLE
Not working for months, none of the fixes and mods here help

### ISSUE THREAD

**Issue by WilliamReed2004** [LoranKloeze/WhatsAllApp#95]
I've installed the extension and this is what it looks like:

![image](https://user-images.githubusercontent.com/29880819/78473428-f62d5600-7740-11ea-91b8-a0f31438bb85.png)

And this is the error that is being put out:

![image](https://user-images.githubusercontent.com/29880819/78473463-37256a80-7741-11ea-9bac-1b5077daaeef.png)

I tried almost any mod or fix but nothing works...

**Comment by nityoday** [comment]
ohhari5336 is working for the fix of https://github.com/ohari5336/WhatsAllApp-Mod . 
After he's done with the fix, you can install that one.

**Comment by rizwansoaib** [comment]
https://github.com/rizwansoaib/whatsapp-monitor

**Comment by LoranKloeze** [comment]
Please check https://github.com/LoranKloeze/WhatsAllApp/issues/104 😊
