### ISSUE TITLE
Still not working

### ISSUE THREAD

**Issue by ZinahBaz** [LoranKloeze/WhatsAllApp#96]
Hi everyone,

actually I cant find a Way to use the tool. Even the Mods are not working.
Does anyone have a solution or a good alternative?

Thank you very much!

**Comment by GZY5409** [comment]
yeah me too

**Comment by Michael-Steshenko** [comment]
Not working..

**Comment by LoranKloeze** [comment]
Please check https://github.com/LoranKloeze/WhatsAllApp/issues/104 😊
